# Generated by Django 5.0 on 2023-12-28 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fkeyapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='joining_date',
            field=models.DateField(null=True),
        ),
    ]
